title       = "simbad"
baseURL     = "https://simbad-cli.tamnd.com/"
description = "A command line for simbad."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/simbad-cli"
